services:
  cube:
    image: cubejs:latest
    build:
      context: .
      dockerfile: packages/cubejs-docker/definite.Dockerfile
    ports:
      # It's better to use random port binding for 4000/3000 ports
      # without it you will not able to start multiple projects inside docker
      - 4000:4000 # Cube API and Developer Playground
      - 3000:3000 # Dashboard app, if created
    env_file: .env
    volumes:
      - .:/cube/conf
      # We ignore Cube deps, because they are built-in inside the official Docker image
      - .empty:/cube/conf/node_modules/@cubejs-backend/
    mem_limit: 8g

  redis:
    image: redis:7
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
